Module CyberZend_SocialLogin<br />Hello World !!!!
<?php
/** @var \CyberZend\SocialLogin\Block\BlockTest $block */
?>

<div class="cyber-social-login">
    <div class="list-social-login">
        <a class="social-button facebook">
            <i class="social-icon"></i>
            <span>Facebook</span>
        </a>
        <a class="social-button google-plus">
            <i class="social-icon"></i>
            <span>Google plus</span>
        </a>
        <a class="social-button twitter">
            <i class="social-icon"></i>
            <span>Twitter</span>
        </a>
    </div>
</div>